# Generated by Django 3.2.7 on 2022-11-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='body',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
