# Generated by Django 3.2.7 on 2022-11-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='author_default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, default='cover_default.png', upload_to=''),
        ),
    ]
